version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Build
          command: *build-android-app
      - run: 
        name: Build android
        command: Date
      - run: 
      name: Build2
      command: *compile-native-libs
