version: 2
jobs:
  build:
    working_directory: ~/Test1
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: yarn install
          command: yarn install
